### ISSUE TITLE
open SSDD数据集下载地址无效

### ISSUE THREAD

**Issue by zhang-pan** [Egrt/yolov7-obb#1]
大佬，您预留的open SSDD数据集下载地址的百度网盘网址打不开，可以提供一个新的网址吗？

**Comment by Egrt** [comment]
> 

百度网盘地址已经更新，旋转框的地址要选择标签中的rbox。

**Comment by Egrt** [comment]
> 大佬，您预留的open SSDD数据集下载地址的百度网盘网址打不开，可以提供一个新的网址吗？

已经在redme中更新地址，xml标签需要选择其中的rbox。
