### ISSUE TITLE
大佬能把数据集转换的代码也放进项目里面吗？感谢！

### ISSUE THREAD

**Issue by 777Zhao** [Egrt/yolov7-obb#14]

**Comment by Egrt** [comment]
另一部分的转换放进tiny版本了

**Comment by 777Zhao** [comment]
> 另一部分的转换放进tiny版本了

没有找到在哪里...大佬可以说一下具体位置吗?

**Comment by Egrt** [comment]
> 没有找到，大佬可以说一下具体位置吗，还有就是v7和v7-tiny的数据集格式也不是一样的，分别是怎么处理的呀？感谢大佬回答
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年5月3日(周三) 下午4:50 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Egrt/yolov7-obb] 大佬能把数据集转换的代码也放进项目里面吗？感谢！ (Issue #14) 另一部分的转换放进tiny版本了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

无非是两种格式,一种是xc,yc,h,w,theat另一种就是四个点的坐标x1,y1,x2,y2,x3,y3,x4,y4，v7-tiny版本和v7分别用的就是这两种不同格式的数据集，你去看annotation.py的区别就行

**Comment by hecheng000** [comment]
> 没有找到，大佬可以说一下具体位置吗，还有就是v7和v7-tiny的数据集格式也不是一样的，分别是怎么处理的呀？感谢大佬回答
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年5月3日(周三) 下午4:50 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Egrt/yolov7-obb] 大佬能把数据集转换的代码也放进项目里面吗？感谢！ (Issue #14) 另一部分的转换放进tiny版本了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你好 请问这两个版本是分别用两种格式的标签做的吗
