### ISSUE TITLE
VOC格式问题，我使用自己的数据集，请问在XML的文件里标签的保存形式应该是什么呢？

### ISSUE THREAD

**Issue by MuBuZe** [Egrt/yolov7-obb#17]

**Comment by MuBuZe** [comment]
作者你好，我看您的ssdd数据集的annotations有好几种，bndbox和rotated_bndbox信息都有，具体的取舍应该怎么用呢

**Comment by Egrt** [comment]
> 作者你好，我看您的ssdd数据集的annotations有好几种，bndbox和rotated_bndbox信息都有，具体的取舍应该怎么用呢

rotated_bndbox包含的角度信息，做旋转的就选rotated_bndbox
