### ISSUE TITLE
关于nms_rotated相关组件安装

### ISSUE THREAD

**Issue by Assassincup** [Egrt/yolov7-obb#2]
我安装了Pytorch1.10.1 以及对应的CUDA11.3环境，在执行python setup.py build_ext --inplace命令的时候，之前有一些错误，已通过查阅资料解决。
现在有以下报错：
1. fatal error C1083: 无法打开包括文件: “stddef.h”: No such file or directory
2. fatal error C1083: 无法打开包括文件: “corecrt.h”: No such file or directory
看网上的教程在电脑上找这两个头文件没找到，卸载重装VisualStudio多次无果，在此向作者大佬请教如何解决，如果您愿意分享编译好的文件，或提出其他安装nms_rotated相关组件的方法，我将不慎感激。

**Comment by Egrt** [comment]
> 我安装了Pytorch1.10.1 以及对应的CUDA11.3环境，在执行python setup.py build_ext --inplace命令的时候，之前有一些错误，已通过查阅资料解决。 现在有以下报错：
> 
> 1. fatal error C1083: 无法打开包括文件: “stddef.h”: No such file or directory
> 2. fatal error C1083: 无法打开包括文件: “corecrt.h”: No such file or directory
>    看网上的教程在电脑上找这两个头文件没找到，卸载重装VisualStudio多次无果，在此向作者大佬请教如何解决，如果您愿意分享编译好的文件，或提出其他安装nms_rotated相关组件的方法，我将不慎感激。

已经上传编译后的文件，适配py38，试试有没有用。

**Comment by Assassincup** [comment]
作者您好，我刚将编译后文件放入nms_rotated文件夹下，启动predict程序显示ImportError: DLL load failed while importing nms_rotated_ext: 找不到指定的程序。看来简单地拷贝编译后文件无法解决问题，十分感谢您如此及时地回复我，我将积极地寻找相关解决办法，如果之后您有其他的方法，还请不吝赐教。再次感谢您的回复。

**Comment by Assassincup** [comment]
我现在找到了我电脑中D:\Windows Kits\10\Include\10.0.19041.0\ucrt下有需要的一系列头文件，但不知道如何加入到编译的路径中，我准备沿着这个方向试着解决。

**Comment by Egrt** [comment]
http://t.csdn.cn/iOXSK 该链接是我写的环境配置教程,可以作为参考，希望对你有所帮助

**Comment by Assassincup** [comment]
作者大佬，按照您的环境配置方法我一次就成功了，非常感谢您的帮助，如果本环境配置教程是您之前就写好放在csdn上的，那我对自己的愚笨以及对您的叨扰表示歉意，如果是您看到我的issuses写的，那我对您的耐心认真表示敬佩以及替之后欣赏您项目的人表示衷心的感谢。后续我会仔细学习您的项目，如果有疑惑不懂之处还请您指点迷津。再次感谢您的帮助！！

**Comment by Egrt** [comment]
太客气了！共同进步！ 😊

**Comment by pitlst** [comment]
对于这个问题我能再询问一些相关的信息么，比如说作者有计划支持将nms_rotated模块升级到支持pytorch1.11版本之后么

**Comment by Egrt** [comment]
> 对于这个问题我能再询问一些相关的信息么，比如说作者有计划支持将nms_rotated模块升级到支持pytorch1.11版本之后么

nms_rotated直接引用自mmrotate,可以看看他们是否更新

**Comment by wyk-study** [comment]
http://t.csdn.cn/iOXSK这篇博客没有了

**Comment by YsanZyh** [comment]
> 作者大佬，按照您的环境配置方法我一次就成功了，非常感谢您的帮助，如果本环境配置教程是您之前就写好放在csdn上的，那我对自己的愚笨以及对您的叨扰表示歉意，如果是您看到我的issuses写的，那我对您的耐心认真表示敬佩以及替之后欣赏您项目的人表示衷心的感谢。后续我会仔细学习您的项目，如果有疑惑不懂之处还请您指点迷津。再次感谢您的帮助！！


请问这个错误DLL load failed while importing nms_rotated_ext: 找不到指定的程序
您最后的解决方法能分享一下或者简单描述一下吗，我今天在跑这个代码也遇到了这个问题，万分感谢！

**Comment by Assassincup** [comment]
> > 作者大佬，按照您的环境配置方法我一次就成功了，非常感谢您的帮助，如果本环境配置教程是您之前就写好放在csdn上的，那我对自己的愚笨以及对您的叨扰表示歉意，如果是您看到我的issuses写的，那我对您的耐心认真表示敬佩以及替之后欣赏您项目的人表示衷心的感谢。后续我会仔细学习您的项目，如果有疑惑不懂之处还请您指点迷津。再次感谢您的帮助！！
> 
> 请问这个错误DLL load failed while importing nms_rotated_ext: 找不到指定的程序 您最后的解决方法能分享一下或者简单描述一下吗，我今天在跑这个代码也遇到了这个问题，万分感谢！

抱歉没能及时回答您的问题，很久没看这个号了，我当时是看了作者大佬csdn上写的环境配置教程https://blog.csdn.net/weixin_43293172/article/details/129049372?spm=1001.2014.3001.5502
虽然您现在大概不需要了

**Comment by YsanZyh** [comment]
> > > 作者大佬，按照您的环境配置方法我一次就成功了，非常感谢您的帮助，如果本环境配置教程是您之前就写好放在csdn上的，那我对自己的愚笨以及对您的叨扰表示歉意，如果是您看到我的issuses写的，那我对您的耐心认真表示敬佩以及替之后欣赏您项目的人表示衷心的感谢。后续我会仔细学习您的项目，如果有疑惑不懂之处还请您指点迷津。再次感谢您的帮助！！
> > 
> > 
> > 请问这个错误DLL load failed while importing nms_rotated_ext: 找不到指定的程序 您最后的解决方法能分享一下或者简单描述一下吗，我今天在跑这个代码也遇到了这个问题，万分感谢！
> 
> 抱歉没能及时回答您的问题，很久没看这个号了，我当时是看了作者大佬csdn上写的环境配置教程https://blog.csdn.net/weixin_43293172/article/details/129049372?spm=1001.2014.3001.5502 虽然您现在大概不需要了

请问我之前用的torch1.7，没有报错，可以正常使用。但是后来更新成了 torch1.8.0之后就报错 ImportError: DLL load failed while importing nms_rotated_ext: 找不到指定的程序 了。
然后按照这个教程执行完 python setup.py build_ext --inplace 后，报错：
`c1xx: fatal error C1083: 无法打开源文件: “/utils/nms_rotated/src/nms_rotated_cpu.cpp”: No such file or directory
error: command 'D:\\software\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
`
请问这是什么问题。

**Comment by Assassincup** [comment]
建议按照作者环境配置要求来，python1.10.1，然后按照链接中配置步骤安装vs2019和相关组件，很多都是版本对应问题。
