### ISSUE TITLE
UnboundLocalError: local variable 'rbox' referenced before assignment

### ISSUE THREAD

**Issue by hecheng000** [Egrt/yolov7-obb#28]

**Comment by liliang77** [comment]
我也是一样的问题，我找了半天后发现，应该是数据集中有些图片没有标注。
解决方案是找到没有标注的图片，重新标，或者在/dataloader.py中的get_random_data函数开始增加rbox=[]就可以了

**Comment by hecheng000** [comment]
好的 谢谢 可以加下联系方式交流下吗



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年07月13日 17:12 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Egrt/yolov7-obb] UnboundLocalError: local variable 'rbox' referenced before assignment (Issue #28) |

我也是一样的问题，我找了半天后发现，应该是数据集中有些图片没有标注。
解决方案是找到没有标注的图片，重新标，或者在/dataloader.py中的get_random_data函数开始增加rbox=[]就可以了
