### ISSUE TITLE
关于自己数据集标注的问题

### ISSUE THREAD

**Issue by Assassincup** [Egrt/yolov7-obb#3]
作者您好，我看到您用的ssdd数据集的标注中有x1,y1,x2,y2,x3,y3,x4,y4这些数据，我在我已知的标注格式中没有见过，,想请问您该使用什么标注工具制作这样的标签。

**Comment by Egrt** [comment]
rbox格式也是可以的[xc,yc,h,w,theta],工具中附带了将rbox转poly的方法 def rbox2poly()。可以使用roLabelImg工具标注。

**Comment by Assassincup** [comment]
请问您的意思是我想要训练自己数据集的话，先用roLabelImg工具标注，然后自己写一个程序调用您的rbox2poly方法将[xc,yc,h,w,theta]数据转化为[x1,y1,x2,y2,x3,y3,x4,y4]数据，生成新的xml标签文件，然后按照原来的训练步骤进行训练。请问我说的正确吗

**Comment by Egrt** [comment]
是的，这部分代码我也写了。请参考[hrsc_annotation.py](https://github.com/Egrt/yolov7-obb/blob/master/hrsc_annotation.py)

**Comment by Assassincup** [comment]
您好，按照您的指导，我这两天完成了自己数据集的制作、训练、以及识别，得到了很好的效果，感谢您的指导。

**Comment by Egrt** [comment]
> 

祝贺！你制作的什么数据集，可以看看检测效果吗？

**Comment by Assassincup** [comment]
我制作的是水表读数框的数据集，还想问一下关于您使用的旋转框检测的算法知识有没有可以学习的资料，希望您能为我指明一下学习的方向，感谢！祝好

**Comment by Assassincup** [comment]
我邮箱发的附件不知道您能否收到

**Comment by Egrt** [comment]
> 我邮箱发的附件不知道您能否收到

收不到，可以直接在issue发图片。可以参考我的博客还有KLD损失的论文。

**Comment by Gggggm78** [comment]
> 请问您的意思是我想要训练自己数据集的话，先用roLabelImg工具标注，然后自己写一个程序调用您的rbox2poly方法将[xc,yc,h,w,theta]数据转化为[x1,y1,x2,y2,x3,y3,x4,y4]数据，生成新的xml标签文件，然后按照原来的训练步骤进行训练。请问我说的正确吗

您好，我也是用rolableimg标注的数据，请问可以分享你转格式的代码给我吗

**Comment by BUTwo** [comment]
> 您好，按照您的指导，我这两天完成了自己数据集的制作、训练、以及识别，得到了很好的效果，感谢您的指导。

大佬，求分享/(ㄒoㄒ)/~~

**Comment by hecheng000** [comment]
> 您好，按照您的指导，我这两天完成了自己数据集的制作、训练、以及识别，得到了很好的效果，感谢您的指导。

你好 可以留下联系方式吗 也打算用自己制作数据集训练 交流一下

**Comment by hecheng000** [comment]
> 是的，这部分代码我也写了。请参考[hrsc_annotation.py](https://github.com/Egrt/yolov7-obb/blob/master/hrsc_annotation.py)
你好 请问如果我是txt格式的标签数据，训练前需要先转化成xml格式吗

**Comment by hecheng000** [comment]
hrsc数据集的类别有哪些啊 看着有点乱

**Comment by jinyu-118** [comment]
> 您好，按照您的指导，我这两天完成了自己数据集的制作、训练、以及识别，得到了很好的效果，感谢您的指导。
您好，请问方便问你一下数据集的制作过程嘛？方便的话 让我加您的联系方式

**Comment by Assassincup** [comment]
> > 您好，按照您的指导，我这两天完成了自己数据集的制作、训练、以及识别，得到了很好的效果，感谢您的指导。
> > 您好，请问方便问你一下数据集的制作过程嘛？方便的话 让我加您的联系方式

抱歉没能及时回复您，很久没看这个号了，数据集制作就是用旋转图像标注工具做的，好像叫relabeling来着，就正常的YOLO数据集格式，细节不太记得了
