### ISSUE TITLE
目标为圆形时 KLD损失与角度的关系

### ISSUE THREAD

**Issue by 476857578** [Egrt/yolov7-obb#4]
请教一个问题：当我检测的目标是圆形的时候，这时候矩形框是正方形的，我希望角度对损失函数不产生影响，也就是说，检测圆形的时候角度对我来说不重要。请问KLD损失会规避这个问题吗，如果不是，应该怎么修改呢？

**Comment by Egrt** [comment]
很有意思的问题，你在标注圆形目标时候，可以将所有的角度theta设置为0，最后训练结果应该会规避此问题。
