### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by VanSu0274** [Egrt/yolov7-obb#6]
运行voc-annotation.py出现如下报错：
Traceback (most recent call last):
File "d:/download/yolov7-obb-master/voc_annotation.py", line 122, in <module>
convert_annotation(year, image_id, list_file)
File "d:/download/yolov7-obb-master/voc_annotation.py", line 59, in convert_annotation
b = (int(float(xmlbox.find('x1').text)), int(float(xmlbox.find('y1').text)), \
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by Egrt** [comment]
用的是否是HRSC数据集，是的话用hrsc_annotation.py

**Comment by VanSu0274** [comment]
> 

不是HRSC数据集，使用的是rolabelimg标定的数据集，坐标为cx cy w h angle

**Comment by Egrt** [comment]
> 请问大佬用的是什么工具标注数据集，我看了大佬的数据集坐标和我的不一样，想参考一下

标注工具可以用RoLabelImg，你的这种标注格式可以参考yolov7-tiny-obb中的voc-annotation.py
